### ISSUE TITLE
How did you preprocess 20news dataset?

### ISSUE THREAD

**Issue by SleepyBag** [JingqingZ/KG4ZeroShotText#2]
I have preprocessed 20news dataset by your playground.py. But I noticed that this file only seperate a document into lines. Then I found that there are lots of blank and meaningless lines in the preprocessed file. Using that file, I got terrible results even for seen classes.

So, I'd like to know how did you preprocess 20news dataset besides running palyground.py?

**Comment by JingqingZ** [comment]
Thanks for getting in touch!

We provided all intermediate data files we used including processed 20news datasets. Please have a check [supplementary](https://imperiallondon-my.sharepoint.com/:f:/g/personal/jz9215_ic_ac_uk/EmI6JPnwLW5Lu33WbQ4nuEUBSkoc9DI9EcHWassF-QxSZQ?e=oxuXI0).

**Comment by SleepyBag** [comment]
It helps a lot! Thank you!

**Comment by SleepyBag** [comment]
Sorry for interrupting again but the given link seems to be unavailable now. It was available several days before. Could you please check it? Thank you!
@JingqingZ

**Comment by JingqingZ** [comment]
Hi, the material is hosted by our College and the College just prevented the sharing link. Please leave your email address and I will share the material directly to your email.

**Comment by SleepyBag** [comment]
Thank you veeeeeeeeeeeery much!
Please send to xueqianming200@outlook.com

**Comment by JingqingZ** [comment]
The material has been shared by email invites.

**Comment by TengfeiLiu966** [comment]
Hello,Sorry for interrupting,I meet the same problem about the supplementary.Could you please sent it to me?my email is liutengfei0821@163.com
Thank you again!

**Comment by JingqingZ** [comment]
> Hello,Sorry for interrupting,I meet the same problem about the supplementary.Could you please sent it to me?my email is [liutengfei0821@163.com](mailto:liutengfei0821@163.com)
> Thank you again!

The material has been shared by email.

**Comment by TengfeiLiu966** [comment]
Thank you very much!

**Comment by uqzhichen** [comment]
Hi Jingqing, thank you for sharing your implementation for this amazing work. May I have the supplementary materials? My email address is zhi.chen@uq.edu.au.

**Comment by JingqingZ** [comment]
> Hi Jingqing, thank you for sharing your implementation for this amazing work. May I have the supplementary materials? My email address is [zhi.chen@uq.edu.au](mailto:zhi.chen@uq.edu.au).

The material has been shared.

**Comment by shenglih** [comment]
Hi Jingqing, would you mind sharing the supplementary with me too? Mine is sh2264@cornell.edu. Thanks a bunch!

**Comment by JingqingZ** [comment]
> Hi Jingqing, would you mind sharing the supplementary with me too? Mine is [sh2264@cornell.edu](mailto:sh2264@cornell.edu). Thanks a bunch!

No problem, has been shared.

**Comment by venusafroid** [comment]
Hi~ would you mind sharing the supplementary with me too? I'm interested in your work. My address is h_n_ing@163.com. Thanks 
 you very much!!
